workspace:
    base: /frontend
    path: src/github.com/yfzm/FlawSweeper_Web

pipeline:
    build:
        image: node:10.15.0
        commands:
        - npm install
        - npm run-script build
    publish:
        image: plugins/docker
        repo: bywind/flawsweeper-frontend
        tags: ["latest"]
        secrets: [ docker_username, docker_password ]
        dockerfile: Dockerfile
